# Generated by Django 6.0.7 on 2026-08-30 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('slug', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('levels', models.JSONField(default=list)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('term_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'vocabularies',
                'ordering': ['slug'],
                'indexes': [models.Index(fields=['revision'], name='voc_vocab_revision_idx')],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=128)),
                ('label', models.CharField(max_length=255)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('external_id', models.CharField(blank=True, default='', max_length=64)),
                ('sort', models.IntegerField(default=0)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='vocabularies.vocabulary')),
            ],
            options={
                'ordering': ['sort', 'label'],
            },
        ),
        migrations.CreateModel(
            name='TermEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_edges', to='vocabularies.term')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_edges', to='vocabularies.term')),
            ],
            options={
                'indexes': [models.Index(fields=['child'], name='voc_edge_child_idx')],
                'constraints': [models.UniqueConstraint(fields=('parent', 'child'), name='voc_edge_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['vocabulary', 'level', 'label'], name='voc_term_lbl_idx'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'level', 'code'), name='voc_term_unique'),
        ),
    ]
