# Generated by Django 6.0.7 on 2026-09-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['-popularity', 'sort', 'label']},
        ),
        migrations.AddField(
            model_name='term',
            name='popularity',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
